dataset:
  name: mnist
  num_classes: 10
  image_size: 28
  pre_size: 28

  interpolation: bilinear
  normalization_type: mnist

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/mnist/train_mnist.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/mnist/test_mnist.txt
    batch_size: 200
    shuffle: False
