ood_dataset:
  name: mnist_fsood
  num_classes: 10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood, csid]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
  nearood:
    datasets: [notmnist, fashionmnist]
    notmnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
    fashionmnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
  farood:
    datasets: [texture, cifar10, tin, places365]
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
    cifar10:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
    places365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
  csid:
    datasets: [svhn]
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_svhn.txt
