name: aircraft_oe

dataset:
  name: aircraft_oe
  split_names: [train, oe, val, test]
  oe:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/aircraft/train_oe.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
