dataset:
  name: mnist6_seed3
  num_classes: 6
  pre_size: 28
  image_size: 28

  interpolation: bilinear
  normalization_type: mnist

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_mnist6/train/train_mnist_6_seed3.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_mnist6/val/val_mnist_6_seed3.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_mnist6/test/test_mnist_6_id_seed3.txt
    batch_size: 200
    shuffle: False
