dataset:
  name: covid
  split_names: [train, val, test]
  num_classes: 2
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/covid_images/
    imglist_pth: ./data/imglist/covid/train_bimcv.txt
    batch_size: 128
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/covid_images/
    imglist_pth: ./data/imglist/covid/val_bimcv.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/covid_images/
    imglist_pth: ./data/imglist/covid/test_bimcv.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
