ood_dataset:
  name: covid_fsood
  dataset_class: ImglistDataset
  interpolation: bilinear

  batch_size: 20
  shuffle: False
  num_classes: 2
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [val, csid, nearood, farood]
  val:
    data_dir: ./data/covid_images/
    imglist_pth: ./data/imglist/covid/val_ct.txt
  csid:
    datasets: [actmed, hannover]
    actmed:
      data_dir: ./data/covid_images/
      imglist_pth: ./data/imglist/covid/test_actmed.txt
    hannover:
      data_dir: ./data/covid_images/
      imglist_pth: ./data/imglist/covid/test_hannover.txt
  nearood:
    datasets: [ct, xraybone]
    ct:
      data_dir: ./data/covid_images/
      imglist_pth: ./data/imglist/covid/test_ct.txt
    xraybone:
      data_dir: ./data/covid_images/
      imglist_pth: ./data/imglist/covid/test_xraybone.txt
  farood:
    datasets: [mnist, cifar10, texture, tin]
    mnist:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/covid/test_mnist.txt
    cifar10:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/covid/test_cifar10.txt
    texture:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/covid/test_texture.txt
    tin:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/covid/test_tin.txt
