network:
  name: arpl_gan
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # Number of channels in the training images. For color images this is 3
  nc: 3
  # Size of z latent vector (i.e. size of generator input)
  nz: 100
  # Size of feature maps in generator
  ngf: 64
  # Size of feature maps in discriminator
  ndf : 64
  ns: 1

  weight_pl: 0.1
  temp: 1.0

  # network used for feature extraction
  feat_extract_network:
    name: resnet34ABN
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    num_gpus: '@{num_gpus}'
