network:
  name: conf_branch_net
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  checkpoint: none
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: ./results/mnist_conf_net_conf_esti/best.pth
    num_gpus: '@{num_gpus}'
