network:
  name: projectionNet
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # network used for feature extraction
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True
    checkpoint: 'results/cifar100_resnet18_32x32_base_e100_lr0.1/best.ckpt'
    num_gpus: '@{num_gpus}'
