network:
  name: godin_net
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  similarity_measure: 'cosine' # value in ['cosine', 'inner', 'euclid']

  # network used for feature extraction
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    num_gpus: '@{num_gpus}'
    checkpoint: none
