network:
  name: mcd
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: ''
  num_gpus: '@{num_gpus}'

  backbone:
    name: lenet
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: ''
    num_gpus: '@{num_gpus}'
