network:
  name: opengan
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # Number of channels in the training images. For color images this is 3
  nc: 512
  # Size of z latent vector (i.e. size of generator input)
  nz: 100
  # Size of feature maps in generator
  ngf: 64
  # Size of feature maps in discriminator
  ndf : 64

  # network used for feature extraction
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    num_gpus: '@{num_gpus}'
