network:
  name: resnet50
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True          # set 'True' to load pretrained model
  checkpoint: ./checkpoints/resnet50-0676ba61-pytorch.pth           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
