network:
  name: resnet18_64x64
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: ./results/cifar10_resnet18_32x32_base_e200_lr_0.1/best.ckpt            # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
