network:
  name: vit
  model: openood/networks/vit-base-p16-384.py
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True          # set 'True' to load pretrained model
  checkpoint: ./checkpoints/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth         # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
dataset:
  image_size: 384
ood_dataset:
  image_size: 384
