network:
  name: vos
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  num_layers: 40
  widen_factor: 2
  droprate: 0.3

  backbone: #for network without feature_list
    name: lenet
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: None
    num_gpus: '@{num_gpus}'
