exp_name: "'@{dataset.name}'_'@{network.name}'_'@{pipeline.name}'\
_'@{evaluator.name}'_gmm0_'@{mark}'"

postprocessor:
  name: gmm
  postprocessor_args:
    num_clusters_list: [3, 1, 10]
    feature_type_list: [flat, mean, flat]     # flat/mean/stat
    alpha_list: [1, 0, 0]
    reduce_dim_list: [pca_50, none, pca_50]   # none/capca_10/pca_50
