dataset:
  name: cifar10_double_label
  interpolation: bilinear
  normalization_type: cifar10
  split_names: [train, val, test]
  num_classes: 12 # actually it's 10 classes but it has 2 groups
  image_size: 32
  pre_size: 32
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/train_cifar10_mos.txt
    batch_size: 128
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/val_cifar10_mos.txt
    batch_size: 128
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/test_cifar10_mos.txt
    batch_size: 128
    shuffle: False
    interpolation: bilinear
