dataset:
  name: tin20_seed4
  num_classes: 20
  pre_size: 64
  image_size: 64

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/train/train_tin_20_seed4.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/val/val_tin_20_seed4.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/test/test_tin_20_id_seed4.txt
    batch_size: 200
    shuffle: False
