ood_dataset:
  name: cifar6_seed3_osr
  num_classes: 6
  pre_size: 32
  image_size: 32

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, osr]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_cifar6/test/test_cifar10_6_id_seed3.txt
  osr:
    datasets: [cifar4]
    cifar4:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/osr_cifar6/test/test_cifar10_4_ood_seed3.txt
