exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

pipeline:
  name: train

trainer:
  name: mos
  # group_config: ./data/group_config/cifar100_group_config.txt
  group_config: Auto # if set to none the program will auto re-compute it
  # group_config is a list that the num of classes in each super classes
  # It should be noted that the configuration of automatic calculation may be inconsistent with
  # the category classification used in training, resulting in errors

evaluator:
  name: mos

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.003

recorder:
  name: base
  save_all_models: False
