exp_name: "'@{dataset.name}'_'@{network.name}'_train_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'"
output_dir: ./results/
save_output: True
merge_option: merge

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

pipeline:
  name: train_ad

trainer:
  name: draem

evaluator:
  name: ad

optimizer:
  name: MultiStep
  num_epochs: 700
  steps: [0.8, 0.9]
  lr: 0.0001
  gamma: 0.2

recorder:
  name: ad
  best_model_basis: image_auroc
  save_all_models: False
