exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'"
save_output: True
merge_option: default
normal_class: 3
output_dir: ./results/
lr: 0.0001

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

lr_milestones: [50]
weight_decay: 0.5e-6
warm_up_n_epochs: 10

R: 0
c: None

pipeline:
  name: train_ad
evaluator:
  name: ad

trainer:
  name: dsvdd

recorder:
  name: ad
  save_all_models: False

optimizer:
  name: adam
  num_epochs: 150
