exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'"
output_dir: ./results/
save_output: True
merge_option: default

mark: default
num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

pipeline:
  name: train

trainer:
  name: cutmix
  trainer_args:
    beta: 1.0
    cutmix_prob: 1.0   # cutmix probability

evaluator:
  name: base

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

recorder:
  name: base
  save_all_models: False
