exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'"
output_dir: ./results/
save_output: True
force_merge: False # disabled if 'save_output' is False
num_classes: '@{dataset.num_classes}'

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0


sample_number: 1000
sample_from: 10000
select: 1
feature_dim: 512  #resnet 512, lenet 120

pipeline:
  name: train

trainer:
  name: vos
  loss_weight: 0.1

evaluator:
  name: base

optimizer:
  num_epochs: 100
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 5.0e-4

recorder:
  name: base
  save_all_models: False

preprocessor:
  name: base

start_epoch: 0
