exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'"
output_dir: ./results/
save_output: True
merge_option: default # disabled if 'save_output' is False
normal_class: 3
lamda: 0.01
dataset_name: '@{dataset.name}'
direction_loss_only: False
learning_rate: 1e-3
metrics: roc_auc
last_checkpoint: 201
continue_train: False

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

pipeline:
  name: train_ad
evaluator:
  name: kdad
trainer:
  name: kdad
recorder:
  name: kdad
  save_all_models: False
optimizer:
  num_epochs: 201
