exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'"
output_dir: ./results/
save_output: True
merge_option: default

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

preprocessor:
  name: base

pipeline:
  name: train

trainer:
  name: base

evaluator:
  name: ece

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

recorder:
  name: base
  save_all_models: False
