exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_lam'@{trainer.lambda_oe}'_'@{mark}'/s'@{seed}'"

pipeline:
  name: train_oe

trainer:
  name: oe
  lambda_oe: 0.5
