exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_dropout"
output_dir: ./results/
save_output: True
merge_option: default

num_gpus: 1
num_workers: 0

pipeline:
  name: train

trainer:
  name: dropout
  dropout_p: 0.5

evaluator:
  name: base

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

recorder:
  name: base
  save_all_models: False
