exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'"
output_dir: ./results/
save_output: True
force_merge: True

dataset:
  # cached features extracted from classifier
  feat_path: './results/tin_resnet18_32x32_feat_extract/feature.npz'

num_gpus: 1
num_workers: 0
num_machines: 1

pipeline:
  name: train_opengan

trainer:
  name: opengan

evaluator:
  name: opengan

optimizer:
  name: Adam
  num_epochs: 100
  lr: 0.0001
  beta1: 0.5

recorder:
  name: opengan
  save_all_models: True
