exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
seed: 0

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

pipeline:
  name: train

trainer:
  name: arpl

evaluator:
  name: arpl

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001

recorder:
  name: arpl
  save_all_models: False
