dataset:
  name: imagenet
  num_classes: 1000
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/train_imagenet.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/val_imagenet.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/test_imagenet.txt
    batch_size: 128
    shuffle: False
