dataset:
  name: cifar100
  num_classes: 100
  pre_size: 32
  image_size: 32

  interpolation: bilinear
  normalization_type: cifar100

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistExtraDataDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/train_cifar100.txt
    batch_size: 128
    shuffle: True
    extra_data_pth: ./data/images_classic/cifar100_extra/stylegan_images.npy
    extra_label_pth: ./data/images_classic/cifar100_extra/stylegan_labels.npy
    extra_percent: 100
    orig_ratio: 0.8
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/val_cifar100.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/test_cifar100.txt
    batch_size: 200
    shuffle: False
