name: cifar100_oe

dataset:
  name: cifar100_oe
  split_names: [train, oe, val, test]
  oe:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/train_tin597.txt
    batch_size: 256
    shuffle: True
    interpolation: bilinear
